### ISSUE TITLE
Script trajectory_figure_ral.m is not working

### ISSUE THREAD

**Issue by minghanz** [utiasSTARS/certifiable-calibration#1]
The file trajectory_figure_ral.m is not working. The functions used in the script are not defined (bot_quat_to_roll_pitch_yaw, GetHomoTransform, GetState, etc). Could you please add those files to the repo?

**Comment by mattgiamou** [comment]
Added them, thanks for pointing this out! Sorry for the inconvenience!

**Comment by minghanz** [comment]
Rapid response! But it seems that some functions are still missing. For example: bot_roll_pitch_yaw_to_quat, bot_quat_to_matrix. I am not sure whether there are others. Could you add the missing files? Thanks a lot.

**Comment by mattgiamou** [comment]
Oops, sorry! Added those two as well, let me know if any others are found!

**Comment by minghanz** [comment]
It seems that DrawAxis function is still missing. Thanks!

**Comment by mattgiamou** [comment]
Added! Hopefully that's the last one.

**Comment by minghanz** [comment]
Still another missing... bot_matrix_to_quat is not found. Could you add that?

**Comment by mattgiamou** [comment]
Added!

**Comment by minghanz** [comment]
It works! Thank you!
